# Use postgres/example user/password credentials
version: '3.8'

services:

  db:
    image: postgres:15
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - ./sql-migrations:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: antlms-user
      POSTGRES_PASSWORD: example
      POSTGRES_DB: antlms

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080