# Use postgres/example user/password credentials
version: "3.8"

services:
  db:
    image: postgres:15
    restart: on-failure
    ports:
      - 5432:5432
    # set this value in you .env file or export it in the shell
    # DATABASE_URL='postgresql://antlms-user:example@localhost:5432/antlms?schema=public&connection_limit=5'
    # Then run "npm run migrate" on host computer to migrate schema with prisma
    environment:
      POSTGRES_USER: antlms-user
      POSTGRES_PASSWORD: example
      POSTGRES_DB: antlms

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080

  s3:
    image: minio/minio
    restart: on-failure
    volumes:
      - ./s3-data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address :9001

  createbuckets:
    image: minio/mc
    depends_on:
      - s3
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://s3:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/antlms;
      /usr/bin/mc anonymous set public myminio/antlms;
      exit 0;"
