# Install using ansible-galaxy install -r requirements.yml
# Running ansible-galaxy collection install -r or ansible-galaxy role install -r will only install collections, or roles respectively.
---
roles:
  # Install a role from Ansible Galaxy.
  - name: geerlingguy.pip
  - name: geerlingguy.docker

collections:
  # Install a collection from Ansible Galaxy.
  - name: community.docker
    version: ">=3.4.8"
    source: https://galaxy.ansible.com