#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running 'npx vue-tsc --noEmit || true' for typescript warnings. Recommended to fix these but not required"
npx vue-tsc --noEmit || true
echo "Running eslint for code smell and bad vue/vueitfy code detection. Mandatory to fix these"
npx lint-staged
